### ISSUE TITLE
0.9.4 - Ubuntu 16.04 64bit Java Errors

### ISSUE THREAD

**Issue by pondsea** [Heat-Ledger-Ltd/heatledger#2]
On a clean install, all i do is edit in the API key info the conf file.

I run heat and i get:

java.lang.RuntimeException: java.io.FileNotFoundException: conf/hardfork-0.9.4.json (No such file or directory)
        at com.heatledger.Hardfork094_TheFix.loadJson(Hardfork094_TheFix.java:54)
        at com.heatledger.Hardfork094_TheFix.loadForkFixes(Hardfork094_TheFix.java:67)
        at com.heatledger.Hardfork094_TheFix.getAccountPublicKey(Hardfork094_TheFix.java:152)
        at com.heatledger.Account.getPublicKey(Account.java:306)
        at com.heatledger.Account.getPublicKey(Account.java:391)
        at com.heatledger.Account.setOrVerify(Account.java:543)
        at com.heatledger.TransactionImpl.verifySignature(TransactionImpl.java:798)
        at com.heatledger.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:728)
        at com.heatledger.BlockchainProcessorImpl.access$500(BlockchainProcessorImpl.java:56)
        at com.heatledger.BlockchainProcessorImpl$1.downloadBlockchain(BlockchainProcessorImpl.java:339)
        at com.heatledger.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: conf/hardfork-0.9.4.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.heatledger.Hardfork094_TheFix.loadJson(Hardfork094_TheFix.java:46)
        ... 17 more

Then: 4 x and sits there.

2017-02-08 13:07:47 INFO: Pushed block 15891245594101046029 at height 14352
com.heatledger.BlockchainProcessor$TransactionNotAcceptedException: com.heatledger.HeatException$NotCurrentlyValidException: Invalid ask order: 8684338696566424166
        at com.heatledger.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:751)
        at com.heatledger.BlockchainProcessorImpl.access$500(BlockchainProcessorImpl.java:56)
        at com.heatledger.BlockchainProcessorImpl$1.downloadBlockchain(BlockchainProcessorImpl.java:339)
        at com.heatledger.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.heatledger.HeatException$NotCurrentlyValidException: Invalid ask order: 8684338696566424166
        at com.heatledger.TransactionType$ColoredCoins$6.validateAttachment(TransactionType.java:784)
        at com.heatledger.Attachment$AbstractAttachment.validate(Attachment.java:54)
        at com.heatledger.TransactionImpl.validate(TransactionImpl.java:841)
        at com.heatledger.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:749)
        ... 10 more

**Comment by pondsea** [comment]
Seems like you need to run from top dir instead of in bin.
